"""empty message

Revision ID: 44dc3646941e
Revises: 2610d834bb7a
Create Date: 2023-05-20 01:56:17.944675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44dc3646941e'
down_revision = '2610d834bb7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_constraint('people_homeworld_id_key', type_='unique')
        batch_op.drop_constraint('people_homeworld_id_fkey', type_='foreignkey')
        batch_op.drop_column('homeworld_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('homeworld_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('people_homeworld_id_fkey', 'planets', ['homeworld_id'], ['id'])
        batch_op.create_unique_constraint('people_homeworld_id_key', ['homeworld_id'])

    # ### end Alembic commands ###
